# if you do not use Apollo, ignore the follow config
################################################## Apollo config start ##################################################
apollo:
  # if use Apollo set this flag to true
  enabled: false #use Apollo? (default:false)
  bootstrap:
    # if use Apollo set this flag to true
    enabled: false #use Apollo?
    namespaces: application #please input the apollo bootstrap namespaces (default:application)
    eagerLoad:
      # if use Apollo set this flag to true
      enabled: false #use Apollo?
################################################### Apollo config end ###################################################

# if you do not use Nacos, ignore the follow config
################################################## Nacos config start ###################################################
nacos:
  config:
    # if use Nacos config set this flag to true
    enabled: false #use Nacos Config? (default:false)
    # need replace
    server-addr: localhost:8848 #please input the nacos config server-addr (default:localhost:8848)
    auto-refresh: true
    group: fizz-gateway #please input the nacos config group (default:fizz-gateway)
    data-id: application #please input the nacos config data-id (default:application)
    type: PROPERTIES #please input the nacos config type (default:PROPERTIES)
    # need replace
    namespace: null #please input the nacos config type (default:null)
  discovery:
    # if use Nacos discovery set this flag to true
    enabled: false #use Nacos Discovery? (default:false)
    # need replace
    server-addr: localhost:8848 #please input the nacos discovery server-addr (default:localhost:8848)
    auto-register: true
    register:
      group-name: fizz-gateway #please input the nacos discovery register group-name (default:fizz-gateway)
################################################### Nacos config end ####################################################

# if you do not use Eureka, ignore the follow config
################################################## Eureka config start ##################################################
eureka:
  client:
    # if use Eureka set this flag to true
    enabled: false #use Eureka? (default:false)
    serviceUrl:
      # need replace
      defaultZone: http://localhost:6600/eureka/ #please input the eureka client serviceUrl defaultZone (default:http://localhost:6600/eureka/)
  instance:
    prefer-ip-address: true
################################################### Eureka config end ###################################################

server:
  port: 8600
spring:
  profiles:
    active: dev
  application:
    name: fizz-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

aggregate:
  redis:
    # need replace
    host: 106.14.134.134 #please input the redis host (default:localhost)
    # need replace
    port: 6379 #please input the redis port (default:6379)
    # need replace
    password: DbQHnY5NvDvCRWDD #please input the redis password (default:123456)
    # need replace
    database: 9 #please input the redis database (default:9)
proxy-webclient:
  name: proxy
aggr-webclient:
  name: aggr
fizz-web-client:
  timeout: 20000
fizz-dubbo-client:
  address: zookeeper://127.0.0.1:2181
log:
  headers: COOKIE,FIZZ-APPID,FIZZ-SECRETKEY,FIZZ-SIGN,FIZZ-TS,FIZZ-RSV

stat:
  # switch for push access stat data
  open: true
send-log:
  # switch for push log data
  open: true